### ISSUE TITLE
Billing: Display usage and next payment

### ISSUE THREAD

**Issue by wceolin** [zoonk/zoonk#10]
```[tasklist]
### Tasks
- [ ] Display usage for current period.
- [ ] Display estimated value ($) for next payment.
- [ ] List previous payments.
```
