### ISSUE TITLE
Users: Add to organization on sign up

### ISSUE THREAD

**Issue by wceolin** [zoonk/zoonk#129]
```[tasklist]
### Tasks
- [x] Add to current school as `student`
- [x] If user already has a Zoonk account, ask them to sign in using their Zoonk credentials
- [x] Create school: add as `admin` user
```
