### ISSUE TITLE
Schools: Handle user permissions

### ISSUE THREAD

**Issue by wceolin** [zoonk/zoonk#130]
```[tasklist]
### Public schools
- [x] Add login button to the navbar
- [x] On login: If user hasn't joined school, then add them to school
```

```[tasklist]
### Private schools
- [x] All pages require authentication
- [x] Registration requires confirmation from school manager (or teacher)
- [x] On login: Send a request to join school if user hasn't joined school yet
- [x] Only admins can approve/deny registration requests
```

```[tasklist]
### Schools
- [x] Only school admins can update school info
```

```[tasklist]
### Tasks
- [x] Update locale
```
