### ISSUE TITLE
Schools: Send email for registration events

### ISSUE THREAD

**Issue by wceolin** [zoonk/zoonk#147]
```[tasklist]
### Tasks
- [ ] Send email when registration is pending approval
- [ ] Send email when registration is approved
- [ ] Send email when registration is denied / user is removed from school
```
