### ISSUE TITLE
Schools: Users: Split view by role

### ISSUE THREAD

**Issue by wceolin** [zoonk/zoonk#148]
```[tasklist]
### Tasks
- [x] List admins
- [x] List teachers
- [x] List students
- [x] List admins pending approval
- [x] List teachers pending approval
- [x] List students pending approval (private schools only)
- [x] Approve / deny pending users for private schools
- [x] Unify views
- [x] Fix active on unified view
- [x] Approve / reject pending teachers
- [x] Approve / reject pending admins
- [x] Update locales
- [ ] Update school users FAQ
```
