### ISSUE TITLE
Schools: Raise Ecto.NoResultsError on not found requests

### ISSUE THREAD

**Issue by wceolin** [zoonk/zoonk#151]
We should raise an error instead of returning `nil` since [Phoenix will automatically show a 404 page in those cases](https://elixirforum.com/t/rendering-404s-through-liveview/30018/11?u=wceolin).

```[tasklist]
### Tasks
- [x] Add custom error view for 404 errors
- [x] Add custom error view for 500 errors
- [x] Returns 404 when a school isn't found
- [x] Check other `get` and `get_by` requests to make sure they return `Ecto.NoResultsError`
```
