### ISSUE TITLE
Schools: Only allow admins to delete schools

### ISSUE THREAD

**Issue by wceolin** [zoonk/zoonk#160]
```[tasklist]
### Tasks
- [x] Deleting school should also delete school users
- [x] Deleting school should also delete child schools
- [x] Deleting school should also delete courses
- [x] Add remove school button to school view
- [x] Remove button should be visible to managers only
- [x] Only managers can delete a school
- [x] Clicking the remove school button opens a confirmation modal
- [x] Modal has a warning that this action is irreversible and it will also delete courses, child schools and users
- [x] Modal has options to confirm deletion or cancel
- [ ] Update FAQ: Can I delete my school?
```
