### ISSUE TITLE
Docs: Add ExDoc

### ISSUE THREAD

**Issue by wceolin** [zoonk/zoonk#168]
```[tasklist]
### Tasks
- [x] Review [ExDoc documentation](https://hexdocs.pm/ex_doc)
- [x] Add guides (or pages, look into the difference between them)
- [x] Split modules into sections
- [x] Add mix tasks
- [x] Publish docs
- [x] Review all modules
- [x] Add publish task to CI to run on release
```
