### ISSUE TITLE
Schools: Add canonical URL for custom domains

### ISSUE THREAD

**Issue by wceolin** [zoonk/zoonk#175]
There are three ways can view a school's page:

- `zoonk.io/schools/:school_username`
- `school_username.zoonk.io`
- Using their custom domain (i.g. `zoonk.mycompany.com`)

```[tasklist]
### Tasks
- [ ] `zoonk.io/schools/:school_username` should have a canonical URL to the custom domain if it exists.
- [ ] `zoonk.io/schools/:school_username` should have a canonical URL to our subdomain if the school doesn't have a custom domain.
- [ ] `school_username.zoonk.io` should have a canonical URL to the custom domain if it exists.
```
