### ISSUE TITLE
Schools: Allow color palette customization

### ISSUE THREAD

**Issue by wceolin** [zoonk/zoonk#181]
Each school has their own visual identity. Since we're building a white label product, we shouldn't be using our own color palette for every school.

We need to add a new configuration to the school settings that allow schools to customize their color palette. For now, let's make it simple and offer only Tailwind's color palette as an option.

```[tasklist]
### Tasks
- [ ] Add color palette options to the school settings page
- [ ] List all Tailwind color palettes
- [ ] Have an option to enable/disable gradient for text
```
