### ISSUE TITLE
Use Tigris (AWS-compatible lib) for image uploads

### ISSUE THREAD

**Issue by wceolin** [zoonk/zoonk#186]
```[tasklist]
### Tasks
- [x] Upload images to Tigris
- [x] Update image path
- [x] Update tests
- [x] Run a background job to optimize the image
- [x] Delete images from the bucket when removing it
- [x] Remove previous references to Cloudflare Images
- [x] Add optimized image to Tigris
- [x] Look into pre-signed uploads
- [x] Remove item from school object after deleting image
- [x] Add school object table after uploading image
- [x] Update image size on school object after optimizing it
- [ ] Use FLAME to run the image optimization on a separate machine (moved to #189)
- [x] Maybe add upload tests back?
- [x] Use school id for folders
- [x] When updating image, remove old one from school object
```
