### ISSUE TITLE
Rethink how UserSelection works

### ISSUE THREAD

**Issue by wceolin** [zoonk/zoonk#193]
We can only add one option to a `UserSelection`. This doesn't make much sense for the step kinds like #141 #142 #161 
```[tasklist]
### Tasks
- [x] Make `answer` an array of strings
- [x] Add `total` and `correct` integer fields
- [x] Calculating score should use `total` and `correct` from now on
- [x] For `readonly` steps, `total` and `correct` will both be `1`
```
