### ISSUE TITLE
i18n Support

### ISSUE THREAD

**Issue by wceolin** [zoonk/zoonk#2]
```[tasklist]
### Tasks
- [ ] https://github.com/zoonk/zoonk/issues/121
- [ ] https://github.com/zoonk/zoonk/issues/122
- [ ] https://github.com/zoonk/zoonk/issues/123
- [ ] https://github.com/zoonk/zoonk/issues/120
- [ ] https://github.com/zoonk/zoonk/issues/124
- [ ] https://github.com/zoonk/zoonk/issues/125
```
