### ISSUE TITLE
Schools: Move delete button to school settings

### ISSUE THREAD

**Issue by wceolin** [zoonk/zoonk#203]
While on it, review tests for school view. They should handle private and public schools like we're doing for courses. Plus, they should test for the course list too.

```[tasklist]
### Tasks
- [x] Remove delete button from school view
- [x] Add tests for course list on school view
- [x] Test the schools menu is active
- [x] Add delete school functionality to the school edit pages
```
