### ISSUE TITLE
Users: System Administrator support

### ISSUE THREAD

**Issue by wceolin** [zoonk/zoonk#26]
Some internal users require special permissions for debugging issues. They need to be able to access all courses, schools, and users added to the platform.

```[tasklist]
### Tasks
- [ ] https://github.com/zoonk/zoonk/issues/27
- [ ] https://github.com/zoonk/zoonk/issues/28
- [ ] https://github.com/zoonk/zoonk/issues/29
- [ ] https://github.com/zoonk/zoonk/issues/127
```
