### ISSUE TITLE
Users: Admin: User list

### ISSUE THREAD

**Issue by wceolin** [zoonk/zoonk#27]
```[tasklist]
### Tasks
- [x] Translate new strings
```

```[tasklist]
### User list
- [x] Only display school users for school admin
- [x] List all users
- [x] Name
- [x] Username
- [x] Email
- [x] Age
- [x] Action: User view
```

```[tasklist]
### User view
- [x] Name
- [x] Username
- [x] Email
- [x] Date of birth
```
