### ISSUE TITLE
Content: Steps: Create

### ISSUE THREAD

**Issue by wceolin** [zoonk/zoonk#68]
```[tasklist]
### Tasks
- [x] Delete step
- [x] Create text step
- [x] Create image step
- [x] List options
- [x] Delete option
- [x] Add option to step
- [x] Update option
- [x] Update option image
```
