### ISSUE TITLE
Stats: Allow school/org to make them open

### ISSUE THREAD

**Issue by wceolin** [zoonk/zoonk#76]
```[tasklist]
### Tasks
- [ ] Add configuration to school settings that allow to make stats open
- [ ] If stats are open, then anyone can see them
- [ ] If stats are closed, then only managers can see them
```
